export const ACCESS_TOKEN = 'Access-Token'
export const USER_NAME = 'Login_Username'
export const USER_INFO = 'Login_Userinfo'
export const USER_AUTH = 'LOGIN_USER_BUTTON_AUTH'
export const UI_CACHE_DB_DICT_DATA = 'UI_CACHE_DB_DICT_DATA'
export const SYS_BUTTON_AUTH = 'SYS_BUTTON_AUTH'
